### ISSUE TITLE
cci/2 tests don't compile on OSX

### ISSUE THREAD

**Issue by chris-heijdens** [ludocode/onramp#1]
Attemping to build test/cci/2-full test-0 throws compiler errors on OSX.

See screenshot
<img width="1578" alt="Screenshot 2024-07-26 at 5 22 08 PM" src="https://github.com/user-attachments/assets/3a92f615-6fac-41cf-a3ef-4d44040b8001">

**Comment by ludocode** [comment]
I think this is now fixed. I don't have a macOS machine to test with though. Thanks for reporting this.

**Comment by chris-heijdens** [comment]
![image](https://github.com/user-attachments/assets/6563922e-2367-43d0-a790-bb2b1db2a7d7)

**Comment by chris-heijdens** [comment]
Also these:

<img width="747" alt="Screenshot 2024-07-28 at 11 12 32 PM" src="https://github.com/user-attachments/assets/61eae213-fcab-4678-9c4b-a16baa8fea60">

**Comment by ludocode** [comment]
Fixed, try it now.
